### PR TITLE
Accept a Date object in addition to strings

### PR DESCRIPTION
**Pull request by wankdanker**
This module does exactly what I need it to do, but the dates I need to work with are already instances of Date. This patch allows one to pass a Date object as an argument to the function.

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Hm.. Good catch. Thanks!

**Comment by tunnckoCore** [comment]
> Remove cli.js reference in package.json

I missed to add it, huh.

**Comment by wankdanker** [comment]
Yeah, I guess so. :-)

**Comment by tunnckoCore** [comment]
Sorry for the delay. 
Published as `Release v1.0.6` and `npm@v1.0.6`

**Pull request merged**
